# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Felix Svensson
title: Friendly developer
email: felix@flixen.se
website: flixen.se

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: klowdo
github_username:  klowdo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: felix-svensson
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: klowdo
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/felix-evolve-rund.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Felix and im a Friendly developer. As a developer i like to explore new things. I like the moto "it should be easy to do right and hard to do wrong" so i like to code in a way that is wasy to follow and read.
  I like eventstourcing and clean architecture.

  I am most skilled in: <mark>dotnet</mark>, <mark>go</mark> <mark>Making Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My real resume written i c#
        link: github.com/klowdo/resume
        # link_text: Project Website
        additional_links:
          - title:  klowdo/resume
            icon: fab fa-github
            url: github.com/klowdo/resume
          - title: Generated pdf 
            icon: fa fa-file-pdf
            url: https://github.com/klowdo/Resume/releases/latest/download/resume.pdf
        quote: >
          Fun project since i hate word documents and always loose canvas logins 

      - layout: top-middle
        title: My nixos-config
        link: github.com/klowdo/nixos-config
        # link_text: Project Website
        additional_links:
          - title:  klowdo/nixos-config
            icon: fab fa-github
            url: github.com/klowdo/nixos-config

      - layout: top-middle
        title: A salary calculator coding test
        link: github.com/klowdo/nixos-config
        additional_links:
          - title:  klowdo/SalaryCalculator
            icon: fab fa-github
            url: github.com/klowdo/SalaryCalculator

      - layout: top-middle
        title: A payment system coding test
        link: github.com/klowdo/nixos-config
        additional_links:
          - title:  klowdo/PaymentSystemCqrs
            icon: fab fa-github
            url: github.com/klowdo/PaymentSystemCqrs

      - layout: top-middle
        title: A toll calculator coding test
        link: github.com/klowdo/nixos-config
        additional_links:
          - title:  klowdo/TollCalculator
            icon: fab fa-github
            url: github.com/klowdo/TollCalculator

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: Chargenode EU
        link: https://chargenode.eu/
        sub_title: Senior Developer / Freelancer
        caption: February 2023 - July 2024
        quote: >
          Chargepoints, OCPP, CPO, Wallboxes, Chargsystems and load balancing...
        description: | # this will include new lines to allow paragraphs
          - The client is an EV charger provider that does all
            development in-house including hardware customer
            portal and down to charger protocols. My focus is creating
            a high scalable system in azure for connecting 100k +
            chargers leveraging the actor model.
          - Also, while maintaining and supporting mainline
            development current system written I dotnet.

      - layout: left
        title: Worldstream
        link: https://www.worldstream.com/en
        sub_title: Senior Developer / Freelancer
        caption: March 2022 - February 2023
        quote: >
            Worldstream offers top-brand dedicated servers and network equipment at highly competitive prices. Check out our solutions for flexible IT deployment.
        description: | # this will include new lines to allow paragraphs
          - The first client was an Infrastructure provider based in
            Netherlands (Same as evolve technology). This system is
            an event-sourced system and traceability is key-focus and
            written I go to gain performance.
          - golang, evensourcing, docker

      - layout: left
        title: Evolve Technology/Afry

        link: https://www.worldstream.com/en
        sub_title: Senior Developer
        caption: March 2020 - August 2022
        # TODO: Break these out to project instead
        description: | # this will include new lines to allow paragraphs
          - Software development in agile projects
          - Identity and security management
          - Productivity and tools improvement
          - First client was a Swedish med-tech company that focuses on pro-active care of patient with live health monitoring. This system was written in C# and built into Microsoft azures cloud services.
          - Second client was a Infrastructure provider based in Netherlands. This system was an event-sourced system where traceability was key-focus and written I go to gainperformance.

      - layout: left
        title: CXC (Deloite Australia)
        link: https://www.worldstream.com/en
        sub_title: Senior Developer / Freelancer
        caption: May 2019 - February 2020
        description: | # this will include new lines to allow paragraphs
          - Application development stream lead.
          - Technical analysis and problem investigation in relation to software platforms at the Cloud Infrastructure layers.
          - Platform and Infrastructure configuration for both the implementation of changes and resolution of problems as required
          - Collaboration with other technology units at Deloitte, Customers and their 3rd party service providers.
          - ITSM process execution including Incident and Problem Management utilizing applications such as VSTS and Jira.
          - Analysis, tracking and monitoring of technical issues including regular reporting and escalation where required
          - Platform and Infrastructure system monitoring utilizing a variety of modern tools including event and log managers

      - layout: left
        title: Collector Bank
        link: https://www.collector.se
        sub_title: Developer 
        caption: July 2016 - January 2019
        description: | # this will include new lines to allow paragraphs
          - Collaborative development of core bank system.
          - Monitor and operating production cloud systems. ensuring an always up system.
          - In charge of Cloud infrastructure and security maintenance and development.
          - Building and maintaining CI/CD
          - Analysing new technologies to investigate improvement of systems speed, reliability and security.
          - Management utilizing applications such as Azure DevOps and Octopus deploy.

      - layout: left
        title: Collector Bank
        link: https://www.collector.se
        sub_title: Developer Azure Integration 
        caption: May 2015 - July 2016
        description: | # this will include new lines to allow paragraphs
          - Direct communication with the origination and analyzing new components to be manufactured or migrated.'
          - Building, testing and deployment of service.
          - Monitor, reporting and updating cloud services components
          - Management utilizing applications such as Team city, Jira and Octopus deploy.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: Self tought
        caption: 1995 - Present
        sub_title: At all time and everywhere
        quote: >

          Established in 1995, Self tought is the oldest education institution in the my knowledge, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading leading methods in not just me but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

      - layout: left
        title: Borås University
        caption: 2010 - 2013
        sub_title: nformation systems
        description: | # this will include new lines to allow paragraphs
          I studied here for a year until i realised that i like coding and i pretty good of teaching myself insted of wasting time in the school

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in  software engineering some of my other interests and hobbies are:
      - Ice hockey
      - Motorbikes
      - Home automation

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
